# 1984组 求学大作战前台服务 academy_canary_home_web
spring:
    profiles:
        # 引入核心配置
       include: core
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
server:
  port: 20464
  tomcat:
      basedir: /data/services/academy-canary-server/home/logs/run